"""Initial migration

Revision ID: 89cf293436f6
Revises: 
Create Date: 2023-05-19 16:15:51.305003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89cf293436f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet_ministers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('img_src', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='cabinet_ministers_pkey')
    )
    
    op.create_table('sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minister', sa.String(), nullable=True),
    sa.Column('positive_score', sa.Numeric(), nullable=True),
    sa.Column('negative_score', sa.Numeric(), nullable=True),
    sa.Column('neutral_score', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sentiments_pkey')
    )
    
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minister', sa.String(), nullable=True),
    sa.Column('tweet', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cabinet_ministers')
    op.drop_table('sentiments')
    op.drop_table('tweets')
