"""Initial migration

Revision ID: 9dfb8e6c6288
Revises: 
Create Date: 2023-05-19 14:48:51.181676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfb8e6c6288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cabinet_ministers')
    op.drop_table('tweets')
    op.drop_table('sentiments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minister', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('positive_score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('negative_score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('neutral_score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sentiments_pkey')
    )
    op.create_table('tweets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minister', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tweet', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tweets_pkey')
    )
    op.create_table('cabinet_ministers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('img_src', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cabinet_ministers_pkey')
    )
    # ### end Alembic commands ###
