version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_USER: db
      POSTGRES_DATABASE: db
    ports:
      - 5432:5432
# psql -h localhost -d db -U db